insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());
insert into tb_category(name, creation_Date) values('Books' , NOW());
insert into tb_category(name, creation_Date) values('Electronics', NOW());
insert into tb_category(name, creation_Date) values('Computers', NOW());