name: Pipeline

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  tests:
    name: Running Tests  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file ./backend/pom.xml

  build:
    needs: tests
    name: Build maven package
    runs-on: ubuntu-latest   

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('./backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build package jar
        run: mvn -B package -DskipTests --file ./backend/pom.xml
      - name: Upload .jar
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./catalog/target/catalog-0.0.1-SNAPSHOT.jar
